name: Deploy to GitHub Pages

on:
  # Trigger on PRs to main
  pull_request:
    branches:
      - main
  # Trigger on pushes to main
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Build PR preview if it's a PR
      - name: Build PR preview
        if: github.event_name == 'pull_request'
        env:
          VITE_BASE_PATH: /pr/${{ github.event.number }}/
        run: |
          npm run build
          mkdir -p dist/pr/${{ github.event.number }}
          mv dist/* dist/pr/${{ github.event.number }}/ 2>/dev/null || true

      # Build main branch if it's a push to main
      - name: Build main
        if: github.event_name == 'push'
        run: npm run build

      # If this is a PR, fetch and build main branch as well
      - name: Fetch and build main branch
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin main:main
          git checkout main
          npm ci
          npm run build
          mkdir -p pr-dist
          mv dist/* pr-dist/
          git checkout ${{ github.head_ref }}
          cp -r pr-dist/* dist/

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # Add comment only on PR
      - name: Comment on PR with staging link
        if: github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            🚀 Staging deployment is ready!
            Visit PR preview: https://trainings.mashlom.me/pr/${{ github.event.number }}/#/er
            Visit main branch: https://trainings.mashlom.me/#/er
