name: Deploy to GitHub Pages

on:
  # Trigger on PRs to main
  pull_request:
    branches:
      - main
  # Trigger on pushes to main
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Build PR preview (this will be handled in the combined build step)
      - name: Build PR preview
        if: github.event_name == 'pull_request'
        env:
          VITE_BASE_PATH: /pr/${{ github.event.number }}/
        run: echo "PR build will be handled in combined build step"

      # Build main branch if it's a push to main
      - name: Build main
        if: github.event_name == 'push'
        run: npm run build

      # If this is a PR, fetch and build main branch as well
      - name: Fetch and build main branch
        if: github.event_name == 'pull_request'
        run: |
          # Store current branch name
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

          # First build PR branch
          npm run build
          mkdir -p tmp-pr-dist
          mv dist/* tmp-pr-dist/ || true

          # Fetch and checkout main
          git fetch origin main:main
          git checkout main

          # Build main branch
          npm ci
          npm run build

          # Prepare final dist structure
          mkdir -p dist/pr/${{ github.event.number }}

          # Move main build to root of dist
          mv dist/* dist/ || true

          # Move PR build to its specific directory
          mv tmp-pr-dist/* dist/pr/${{ github.event.number }}/ || true

          # Print directory structure for debugging
          echo "Final dist directory structure:"
          ls -R dist/

          # Don't fail if any of the copy commands failed
          exit 0

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # Add comment only on PR
      - name: Comment on PR with staging link
        if: github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            🚀 Staging deployment is ready!
            Visit PR preview: https://trainings.mashlom.me/pr/${{ github.event.number }}/#/er
            Visit main branch: https://trainings.mashlom.me/#/er
