name: Build Environments

on:
  pull_request:
    branches: [main]

jobs:
  build-environments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          path: pr-branch
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          path: main-branch
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            pr-branch/package-lock.json
            main-branch/package-lock.json

      # Build main branch
      - name: Install dependencies (main)
        working-directory: main-branch
        run: npm ci

      - name: Build main
        working-directory: main-branch
        run: npm run build

      # Build PR branch
      - name: Install dependencies (PR)
        working-directory: pr-branch
        run: npm ci

      - name: Build PR
        working-directory: pr-branch
        run: npm run build

      # Organize dist folders
      - name: Organize distributions
        run: |
          mkdir -p combined-dist
          cp -r main-branch/dist/* combined-dist/
          mkdir -p combined-dist/staging
          cp -r pr-branch/dist/* combined-dist/staging/

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./combined-dist
          force_orphan: true
